package hidden_states;

import flixel.FlxG;
import menus.MainMenuState;

using StringTools;

class AmiGwainSagaState extends MusicBeatState
{
	override function create()
	{
		super.create();
		trace("
			                                                                                                                                                                                   .^!~.       .::::::^::?#J:~!~:                                                                                 .::                             .:~~!!!!!!!!!!!!!!!!!^    !B^                                                 
                                                                                                                                                                                 :~!^.       .:::::^^:.:Y#7^!!^.                                                                               .:^:.  .                       .:^~!!!~~~!!!!!!!!!!!!!!~.    :G~                                                 
                                                                                                                                                                              .~?7^        .::::^!~::.^PB!^!~:                                                                               :^^:.  .:.                   .:^~~!!!~^^^~~!!!!!!!!!!!!!~:     .P!                                                 
                                                                                                                                                                            .!J7:         .::^^!~^:::~BG!~!~.                                                                             .^~~:   .:.                  .:^~!!!~^:::^~~!!!!!!!!!!!!!!!:      .P!                                                 
                   ..:^^^~~~^^:.                                                                                                                                          :!?~.          ::^^^^:::::~BB!~!^.                                                                           .:^~~:   .^:.                .:~~!~^::. .:~!!!!!!!~!!!!!!~!!!~.      .P!                                                 
                .:~!!!!!!!!!!!^:.                                                                                                                                       ^!!:           .:^:::::::::~BB!~!^                                                                           .^~!~:   .^^.              .:^^~^:..   .:~!!!!!!!!~~!7!!!!!~!!!~:      .P~                                                 
              .~!!!!!!!!!!!!!!!!~~:.                                                                                                                                  :!~.           .:::.::::::::^B#7~!:                                                                  .......:^~!!~:   .^^.             .:^^:..      :^~!!!!!!!!~~!??!!!!!~~~!!~:      .G~                                                 
             ^!!!!!!!!!!!!!!!!!!!!!!~:                                                                                                                              :~~.           .:::..:::::::::5&?~!:                                                            :^!?JJYJJJJJYYYYJ?~.  .^^.           .::::..       .^~!!!!!!!!~~~7JY?!~!!!!~^~!!~.      :G^                                                 
           .~!!!!!!!!!!!!!!!!!!!!!!!!!~:                                                                                                                          .~~.           .:::..::::::::::?@Y~!^                                                       .:~?Y5YJ7!^:.  .^~~!!~:.:..::.          ..::..       .:^~!!!!!!!~~~!7JYY?!~!!!!~!^.~!!~.      ~G^                                                 
           ~!!!!!!!!!!!!!!!!!!!!!!!!!!!!^                                                                                                                        ~!:           .:::..:::::::::::~#B!!!:                                             ..    .^7J5Y?!^.      .:~!!!!~:   .::.           ..        .:^~~!!!!!!~~~!7?Y5YJ!~~!!!!!!!~. ^!!^       7G.                                                 
          :!!!!!!!!!!~^::!!!!!!!!!~:.  ..                                                                                                                      :!^            .:^:.:::::::::::::5&?~!~.                                           ..  .^7Y5J!^.        .:~~!!!!~:   .::.                    .:^~!!!!!~~~~!!?Y5#BJ!~~~!!!!!!!!!^  ^!!:       YY                                                  
          .::::^~^:..   :!!!!!!!!!!!~:                                                                                                                       .~^            .:^~^::::::::::::::!&G!~!^                                         .:.  :7YJ!:.         .:~~!!!!!~:   ...                ..::::^~!!!!~~~~!7JY5YJ7^?Y~~!!!!!!!!!!!!:  ^!~.      :G7                                                  
             .^.      .^!!!!!!!!!!!!!!~:                                                                                                                    ^?7            .:^^^:::::::::::::::Y@J~!!^                                        ::. .~7~.          .:^~!!!!!!^:    ..              ..:^^^^~~!!~~~~!7?Y55Y?!^::::^Y!~!!!!!!!!!!!~.  ^!:       !B:                                                  
              ^     .^!!!!!!!!!!!!!!!!!!^                                                                                                                 .?!^~           :~!^::::::::::::::::^B#7~!!:                                      :^.   ..           :^~!!!!!!!^.                  .:^~~!~~~~~~~~!7?Y555J7~^:::::::::JJ~!!!!!!!!!!!^   ~~.       P5                                                   
              ::  :~!!!!!!^^^^^^^^^^^^^^^....                                                                                                            ^J~  ^.       .:~~^::::::::::::::::::!&P~!!!:                                    .^:               .^~!!!!!!!!^.                .:^~~!!!!~~~~!7JY5P5J?~^::::::::::::::?P!~!!!!!!!!!~.  .~:       ~#~                                                   
               :::~!!!!!!!.^~^^^^.:^^^^^:~^^^~^                                                                                                         7Y:    .:::::^^^^:::::::::::::::::::::?@Y~!!~.                                  .^^.   .         .:~!!!!!!!!!^.             .::^~~!!!~~~~!7JY555J7~:..    .::::::::::::?#7~!!!!!!!!!^   :^       .GP.                                                   
                   .::~!!!.~^:~: .~^^^^^^!   ~~                                                                                                       .YJ         ....::::::::::::::::::::::::?@Y~!!~.                                .^^:   ..       .:^~!!!!!!!!!~:           .:^~~!!!~~~~!7JY5P5J7~:.        .:::::^^:::::::?#7~~!!!!!!!~.   ^.       ?@~                                                    
                     :~~~~.^~^^~^.~^^^^^:~^^^~^                                                                                                      :57             :::::::::::::::::::::::::?@J~~!~.                               :~^   ..       :^~!!!!!!!!!!~:        .::^~!!!!~~~!7?Y5P5J7~:.            .::~JGBBBG57^:::J#!7!!!!!!!!^   .:       !&Y                                                     
                                                                                                                                                    :P!            .::::::::::::::::::::::::::?@Y~!!~.                             .^~.   ..     .^~!!!!!!!!!!!~:      .:^~~!!!~~~~!?Y5P5J7~^:..               :^Y&@@@@@@@@B7::Y&B#?~!!!!!~.  .:       !&5.                                                     
                                                                                                                                                   :P~            .:::::::::::::::::::::::::::!&5~!!~.                            :~^   .:.   .:~!!!!!!!!!!~~~^::^~!7????77!~~~!?Y55Y?!^::::..                .!B@@@@@@@@@@@@5^5@@&J!!!!!~.   .       J&J                                                       
                                                                                                                                                  :P!            .:^::::::::::::::::::::::::::^BG!!!~.                          .~~:   ::   .^~!!!!!!!!!!~~!?5G#&@@@@@@@@&&#GPGBY7~^::::::.                   !#@@@@@GBB??5#@@B&@@&G7~!!!:   .      ^PB!                                                        
                                                                                                                                                 ^G!.. ..        :^:::::::::::::::::::^^^::::::5&7~!~.                         :~~.  .:. .:^~!!!!!!!!!!~^7P#@@@@@@@@@@@@@@@@@@@@#5!:::::::                   .B@@@@B7:B5~~~7&@@@@@@#7~!!^          7BY.                                                         
                                                                                                                                                .G!           . ::::::::::::::::^~7?Y5555Y?^.::7&Y~!~.                        ^!^.  .^::^!YY?!~~~~~!~~:^Y&@@@@@@@@@@@@#BB#@@@@@@@@@G?^::::                   7@@@@G^.~#J~!~~5@@@@@@#!~!~.        ^55^                                                           
                                                                                                                                                JY             .:::::::::::^~7J55YJ??77??JYGJ..^#G!!!:                      .^!^.  :~^~!!~P@@&B5J7!~:^~G@@@@@@@@@@#PJ!^:.!&P???Y5G&@@#J^::.                  Y@@@B~..7#?~!~~7#@@@@@B!!~.       :J5~                                                             
                                                                                                                                                PJ             ::::::::^!JYP5J7~^::::::^!??JBJ .5#!~!^                     .~!^  .^!!!!!!~J@@@@@@&#BGB&@@@@@@@@@G!:......5#!~~~~~~!JG&@#?^:                 :B@@&~.:.J&7~~~~~B@@@@@G!~.      :7J~                                                               
                                                                                                                                                ^J7^:..       .^^~!!?J55Y?!^::::::::::::^???JG^ ~&Y~!~.                   :~!^..:~!!!!!!!~!#@@@@@@@@@@@@@@@@@@@5:...:::.^#P~!!!!!!~~~75@@P^.                7#&@J..:.Y#!~^~^^G@@@@&J^.     .!?~                                                                 
                                                                                                                                                  ^GP7??77777?JJJJ??7!^::::::::::::::::^!???JG^ :G#!~!^                  :~!~.:~!!!!!!!!!!~Y@@@@@@@@@@@@@@@@@@G:.::::::.!&Y~!!!!!!!!!~~?#@5:                YG#P:.:.:YB!:^^.:Y@@@@#~    .~?B!                                                                   
                                                                                                                                                   ^B!  ..::::...:::::::::::::::::::::^!?J5P57.::?@J~!~.                :!!~~~!!!!!!!!!!!!~!G@@@@@@@@@@@@@@@@#~.:::::::.!#?~!~~!~!~~~~!~!G&!                JJG!.:::.5G:.:.:.J@@&BG  ^7Y5Y75G.                                                                  
                                                                                                                                                    ^5?.          ..:::::::::::::::^~7J5PY7^..:::^#B!~!^               :!!!!!!!!!!!!!!!!!!!~7B@@@@@@@@@@@@@@@J.::::::::.!#?~!~~~~~~!~~~~~!BG:               ^~!:::.. PY... . Y@&JYGJPGP?!~~!GY                                                                  
                                                                                                                                                     .!YJ~:          .:::::::::^~!7JYYJ!^..:::::::J@?~!!:             ^!!!!!!!!!!!!!!!!!!~~~!5&@@@@@@@@@@@@@#^.::::::::.~#?~~~~~~^~^^~^~^~7B!               .:..:.   GJ . . .G@G!7J?7!~~~~!~7P:                                                                 
                                                                                                                                                        :~7?7~:.     .:::^^~!7?JJJ?!^:.:::::::::::~&P~!!~.           ^!!!!!!!!!!!!!!!!!~~!?YY?7P@@@@@@@@@@@@P:.::::::....5J^^~^~^^^:^:^^:^:P!               .:::.    P7     :#@J~~~~~!!!~~!!~?!                                                                 
                                                                                                                                                           .^!7??J?7!!!!7??77!~^:::::::::::::::::::5&7~!!~.         ^!!!!!!!!!!!!!!!!~~7Y5J7~~~~J#@@@@@@@@@@P:.:::...    ?5:^:::.:.::.:.:::G!               .::.     5!     7PG?~!!!!!!!!!!!~7J                                                                 
                                                                                                                                                                 :?YPGG5J?7!!!!!~~~^^^^::::::::::::~#5~~!!~.       ^!!!!!!!!!!!!!!!~!?55?!~~!!!!~7&#&@@@@@@@B^.:..       :B~:.:... . .... :G~               .::      J7    .?^Y7~!!!!!!!!!!!~7Y                                                                 
                                                                                                                                                                      .::^!?7!7??????JJJ?JJJ?77!!!!~JB7~~~!~:     :!!!!!!!!!!!!!!~~?YJ7~~!!!!!!!~5#~~Y#@@@@@@?..          YP .. . .    .  ^B:               .::      ^J^^:..::?!!!!!!!!!!!!!~75                                                                 
                                                                                                                                                                          :~.         .:::~7??JJJJJJ?GY~~^~!!^.  .~!!!!!!!!!!!!~~?5Y!~!!!!!!!!!~!#Y:::^?B@@@@#!           .G7             7P                .:::       ..:::::!!!!!!!!!!!!~~~?5                                                                 
                                                                                                                                                                         .~~.          :. .~~~~~~~~~~7G7!^.^!!~..^!!!!!!!!!!!~~?P57~!!~~!!!!!!!~J&~:::::^5##@&#7           :G!            G7                 ::::.    ..::::::!!!!!!!!!!!~^~~?Y                                                                 
                                                                                                                                                                         :~^           :. .~!~!!!!!!!~JY~!^.:~!!~~!!!!!!!!!~~7557~~!~::~!!!!!!!~PG:::::::^~!JY?5!           :P7          7G.                 .::::::::::::::::7!!!!!!!!!!^.!~JJ                                                                 
                                                                                                                                                                         ^~.           ^. .~!!!!!!!!!!!?7~!^. :~!!!!!!!!!~~!Y5?!~~~^. ^!!!!!!!~!#Y:::::::::::::^!^           .YJ:       !G^                    .:::::::::::::^J!!!!!!!!!~ .!~57                                                                 
                                                                                                                                                                        .~^        .   ^: .~!!!!!!!!!!!!?!!!~: .~!!!!!!!~7PBY!~^.^~. .~!!!!!!!~?&7::::::::::::.                ~?~. .^7JJ:                       ::::::::::::^J!!!!!!!!~. :!!G^                                                                 
                                                                                                                                                                        ^~:       .:  .~: .~!!!~!!!!!~^::^!!!~^:~~!!!!~~J#G7~^. .~:  .~!!!!!!~~Y&~::::::::::.                        .:.                          .::::::::::^7!!!!~~!~:  :!!G.                                                                 
                                                                                                                                                                       :~^        ^:  .~: .~!!!!!!^:.   ..^!!!!~~~!!!!~J#J~^.   ^~.  :!!!!!!!!~PB^::::::::.                                                         .::::::::~7~!!~:~!:   ^~?Y                                                                  
                                                                                                                                                                      .~~:       :!.  :!: .~7!~:.   :^:..  :!!!!!!!!!~JB7^:     ~^   ^~!!!!!!~!BG::::::::.                                                            ..::::^?!!~^.^!:   .~~J~                                                                  
                                                                                                                                                                      :!^       .~~.  :!^::^:    .:^^.      ^~!!!!!!!7BJ:.     .~:  .~^!!!!!!~!B#Y~::::::                                                                  ^J7!~: ^!:    :!!J.                                                                  
                                                                                                                                                                     .~~.      .~!^  .~!:.   .:^^:.          :~!!!!!~!5:       :~.  .^:!!!!!!~!#J?PY!:::.                                                                 !Y7~^. ^!:     ^!77                                                                   
                                                                                                                                                                    .~~:       ^!!~::..  .:^^^:.              .^!!!^ J!        ^~.  .^:!!!!!!~!B?:^75Y~::                                                               ^JJ!~:  :~:     .~~?:                                                                   
                                                                                                                                                                    ^!^       ^!!^.   .:~7!^.                   :^: .Y.        ^^   .^:~!!!!!~!B7::::!??~.                                               .^7:         .7J7~~.  ^~.      ^!!!                                                                    
                                                                                                                                                                   :!~.     .:^:   .:~J55~                       :^^?!         ^^   .:.~!!!!!~!G7::::::^!7~.                          .:~^:.           .::..        .~?7~~^   ^^.      .~!7:                                                                    
                                                                                                                                                                  .~~.   .::.  ..:~?Y5J!^.:^^~~!!77???JJJJYYYYYJJ?7!5~         ^^   .:.~!!!!!~!G7::::::::^~!^.                        .::^~!~~^:                  .~?7!!~.   ::        ~!!!                                                                     
                                                                                                                                                                 .~~:  :^^.     .7PGPYJJY55PPPPPPPPPPPPPPPPPPPPPPPP5Y:         :^    : ^!!!!!!!P7:::::::::::^^::.                                               .~7???!^    :.        :!!!:                                                                     
                                                                                                                                                                .~!^:^^:.        .^!7J5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.         :^    . :!!!!!!~P7::::::::::::::^::.                                          .^77!^:^~!7!^..         .~!!~                                                                      
                                                                                                                                                            .::~7?7!?7^::::::::::...  .:!YPPPPPPPPPPPPPPPPPPPPPPPPPPJ          .^      :~!!!!!~57::::::....:::::::::.                                   .:^!?JJ?!!!!!!~^^~7~        .~!~~.                                                                      
                                                                                                                   ...:::^^^^~~~~~~~~~~~~~~^:::....  .^~~~^^^^::.    :!7!^:::::::::::::...^7Y5PPPPPPPPPPPPPPPPPPPPPPJ     .:    .      .~!!!!!~J?:::.         .:::^:::!:                   .::^~~!!!!~^^^~~~~~^^^^^^^^:::::J:       ^!~:~                                                                       
                                                                                                               :!!7!!!777!!!!!!!!~~~~~~~!!!!!!!!777!7!:....            .~77~::::::::^!7???JJY5PPPPPPPPPPPPPPPPPPPPPP5.    :!:           ^!!!!!~7J:.             ..:::YG5J?!^.     ..:^!77????77!~~^^:::::::::::^^^^^^^::^^!?:      :!~.~^                                                                       
                                                          ...:::::::::.. ......                              .^^.    ::::::::::::::::::::::::::::^!?7^                    :!7!^:::::~JPP55PPPPPPPPPPPPPPPPPPPPPPPPP5P^    ^!~:          :!!!!!!!!.                 .^BGPPPPPP5J77??77!~^^::::::::^^~~!77?J?JJJY77~~^.. ^?^:.      :!^ :7.                                                                       
                                             ..:^~7??7?????777!!!!!~~~~~^^^^^:::..:^~~~~~!!~~!~~~^^^:::^^^^^^^7Y5Y7^..:::::::::::::::::::::::::~?Y7:                        .~77~:::::^7J55YYPPPPPPPPPPPPPPPPPPPPY7^Y7   .~!!~~.        .~!!!!!!~  .::^~~!!!!!!!~~:.:BGGGGP5Y?!^:....::^~~!7??JYY55PPPP555J57?~~~.:   ~?!.       .~^  7~                                                                        
                                   ..:~!7JY55555YJ?7!!^.~7?7~?YYYY555PPPPP5555YJJ??7777!!!~~~~~~^^::....   ...:YPPGG57::::::::::::::::::::::^?557.                             :!?7~:::::~?55JY5PPPPPPPPPPPPPPPP?^:!PY   .~!~~7J~.       ^!!!!!~!Y555YJJJ????????JYP55Y?~:.   .^~!?JY55PPPPPPPPPPPPP555Y5JY?77^~.:  :??!~:      .~:  ^?                                                                         
                          .:^~7?Y5PPP55Y?7~^^^^^^~^7?JJ7YY55YP55P5PPPPPPPPPPPPPPPPPPPPPPPPP5555YYJJ?????JJYY555PPPPPPGGJ~::::::::::::::::~?5GG7.                                 .!JJ!^:::^7YP5J5PPPPPPPPPPPPG5~:75?^Y~  :!~!J?^7J~      .~~!!!~!!^^::::::::::::::~P^:: .^~?Y5PPPPPPPPPPPPPPPPPPPPPP5P55YYJ7J^!:..^Y57~!!:     .^.  :Y^                                                                         
                  .:^!7JY5PPPYJ7!~^:.:.:!7^.!YY~~Y557J555J5PPP55PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPBBJ^:::::::::::^!5B#B5~.                                     ^?J7^:::^?PP5Y5PPPPPPPPPGJ:!5J:  :7. ^~7Y7^::^J?:     ^~~!!~!~::::::::::::::::7B^ .!GGGGPPPPPPPPPPPPPPPPPPPPPPPPP555J57J!!~.7J5P57!~~.    .^.  .YJ                                                                          
        .:^~7?JY5PPP5Y?7~^:::^^.!JJ~:J55~~55Y^?PPJ75PPYYPPP55PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG#P~::::::::::7P##G7:.                       .                .~??~:::!5G5J5PPPPPPPG7^YP~   .^!^.^?Y!::::::?G?^   .~~~!!~!^:::::::::::::::JG.  YBPPPPPPPPPPPPPPPPPPPPPPPPPPPP5PY5JJ?~?755?!~!JJ7~.   .:.  .55~                                                                          
 ^!7?YPPGGPP5J7~^^: .:^^.7Y5?!5P5!?P5Y~J55J75P5?YPP5JPPPP5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#B~::::::::..:^~!7??7!^:.                  ^^                  ^JJ~::^YGP?YPPPPPP!~GY.   :!!^::!7^:::::!YJ~^7?~. .~^~!~~^:::::::::::::::5P .!#GPPPPPPPPPPPPPPPPPPPPPPPPPPP5P555JY7PGY7~~~!~~!J?:  .:   .5Y77                                                                          
PGG5J7~^:.    :^: 77?7!P55?JP55?55PYJP5PJYP55YPPP55PPP5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#G^::::::.        .:~!7??7!^:.            77                :~?5GB5~.:7GGJYPPPG7!B?    ^7~::::^::::^7YJ~::. :!J!::^^!!~^::::::::::::::^#J.:PBPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP55YPPPPYYYJ7!~~!~~7?!..   :5J~7?                                                                          
:.     ...^7:~!?Y!Y7Y5Y5JP5555P5P55P5P5P5555P5P5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#P^::::.               .:^!7??7~:        JY.         .:^!?Y5PPPPPGB?..^5BJYPGJ!B7    :?~:::::::::75Y~:::.    .~?7!:~!~^^:::::::::::::Y#~:7#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5P5GBG5!::^7J5Y?~~!~!??:  !57~~7J                                                                          
 .^!: ~7Y!:J?57?5JPY555P5P5PP5P5P5PP5P5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP&Y::::                      .^!7?!:    :5P~ .:^~!7JY55PPPPPPPPPPPPG5^ .YGJPP!B?    :?~::::::::!55!::::.        .~~~~~^^::::::::::::7&J:^PBPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY?~^^:.   .!5P?~~!~!?77Y!~!~!Y.                                                                         
YJ:^JYY^7YY57Y555JP5P55P5P5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG&?:^.                          .^~~^!7JPPY~YPPPPPPPPPPPPPPPPPPPPPPGG~ :PJ??GY    .7~:::::::~J57:::::   ...       ...:::::::::::::~BB~:7#PPPPPPPPPPPPPPPPPPPPPPPPPPPGG5J!^.             ~PP7~!~!?7!~!!!!Y^                                                                         
^?YYJ~YY5YJP5P55P5P5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP55555PPPPPB#~:.             ...:::^^^^^^^^^^JPPPPPPG7?PPPPPPPPPPPPPPPPPPPPPPPGG77~.?JG.    ~!:::::::75J^::::. .:::.            ..:::::::::^P#7:^GBPPPPPPPPPPPPPPPPPPPPPPPP5Y?7~.                  .JBJ!~!~~!!!!!~J7                                                                         
J5JJ5Y5J555P5P55P5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP555YYYJJJJ?JJYYYYYYYYYY55PPPPPPPP#P:        ..::^^^^^^^^^^^::::::?PPPPPPPPG7?5PPPPPPPPPPPPPPPPPPPP5Y?~. :JG7    .!^:::::^J5!:::::.:^^:.                 ::::::::J&J::?#PPPPPPPPPPPPPPPPPPPPP5Y?!~~.                       ?#Y!~!!!!!!!~!Y.                                                                        
YPY555P55P5P5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5555YYYYYYY5555PPPPPPPPPPPPPPPPPPPPPPPPPP&J   ..::::^^^:::::::::::::::^YGPPPPPPPPGGJYPPPPPPPPPPPPPPPP5Y?~:     ~PG.    :~:::::^YY^::::^^~~:.                    .:::::?#5^:~GGPPPPPPPPPPPPPPPPPP5?!^^~^^.  .                      JBJ!!!!!!!!!~5^                                                                        
YPPP55PPPP5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP55555PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG#^.::^:::::::::::::::::::::!PGPPPPPPPPPPGBPPGGPPPPPPGGGGP57:.        7&Y     :^::::^JJ^::^~~!^.          ...    ...:::::~!!?B5^:^5GPPPPPPPPPPPPPPGPY7~:::!!^::.:.                       .5P?!!!!!!!!^?J                                                                        
PP55PPP5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP555YYY555PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#5:::::::::::::::::::::::^JGPPPPPPPPPPPPPPBGGBBBGG5Y?7~^.           .P@!     :^::::!?::^~!~:.        ..:::. ..:::::^!?JJ?~!GY^::JGPPPPPPPPPPPPPGP7^::::~7!.!?:                           ~PY!!!!!!!!~^5:                                                                       
5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP555YYYYY555PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#!:::::::::::::::::::::~5GPPPPPPPPPPGGGGPP5J?!^:.                 .J##:     :::::^~^~~~:.        .::::::..::::^!?Y5J7~^~!PJ:::7GPPPPPPPPPPPPGGJ^^^::!?~^^^?^..                           ?J?^::::^^~:J?                                                                       
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP555YYYYYY555PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB5::::::::::::::::::::7PPPPPPPPGGGP5?!~:.                         ?P#G     .::::^~~^:.       ..:::^:::::::^~?Y5Y7~:^!?7~5?:::7GPPPPPPPPPPPPPPY7~::~?~:!~^J?::.                           :7?.        :P:                                                                      
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP555555PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGBBBGGGPPPPPPPPPPPPPPPPPPPPPPPPPPB!:::::::::::::::::~YGPPPPPGGPJ!^.                              !PP&Y     .:::^^:.       ..:::^:::::::~7Y5Y?!^~!7?!^. ??:::7GPPPPPPPPPPPPPG5!.:!~^.^YY7?Y^                               ~?          ?J                                                                      
PPPP55555555555YYYYYY55555PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGB####BBGP55555PBBGGGGGGPPPGGGGGGGBBBBBGG#?:::::::::::::::^?PGPPPGB57^                                  ^5PP@7     .^::.   ...::::::::::::^!?5GBGY?!!77~^.    77:::7GPPPPPPPPPPPPPGJ..7?^.:?5P7!5^.    .                          ~?          :5^                                                                     
PPPPPPPPPPPPPP555555555PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGBB###BG5Y?7!~^^^^^^^^^!5#&G5PP5555YYJJ?7!~~^:..YY:::::::::::::^75GPPGBG?^                                    ~5P5G&~     ::....:::^::::::^~!?Y5PP5Y?!^:...         !~::^JPPPPPPPPPPPPPGGJ.~Y?. 7JYP?75! :~:::.                          7J.          75                                                                     
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP555YYYY5PGBBBBBGPYJ7!^:::::::^^^^^^^^^^^~YG?.                  !P^:::::::::::~YGGPGBP!.                                    :JJ5P5B#^    ::::::^::::^~!?Y5PP5Y?!^.                .~^::7PPPPPPPPPPPPPPGP5~?P7 .J55P5YJ!~~J^.~!                          .Y?^           5?                                                                    
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5555YYYJJJ???77!!~~^^^~!7?YYYYJ7!!!~^^:...               ...::::~5G?                  57:::::::::::^^~!YP!                                     .!5?5P5PGP~:::::::::::^~7JYYJ7~^.                       7B: !BPPPPPPPPPPPPPPPPJ5P! :YP5PPY?J7~YJ^!?. .                        ~5!!:          :P^                                                                   
PPPPPPPPPPPPPPPPPPPPPPPPPPP55YYJJ?777!!~~^^^::::...........::^~7?YY5YJ?!~:.    :^^^:                            ^Y5!                ^5^:::::::::::::YY:                                    :.^5Y5P55GJ7~::::::::^!7?7~^.                             :#7 :BGPPPPPPPPPPPPPPPGP~ :YP5PPYYP5JY57^7^ .^                       .5J~!~.          !P.                                                                  
BBBB#######&&##&&&&#####&#G?!~^::..:~~!77???JJJJJJJY?7777????77!~^:.           .!^^:                              :JY~               7Y::::::::::::!Y                                  .  ^J7Y5J555PB7!~::::^!?J7~:                                   PP  ?#PPPPPPPPPPPPPPGP~ ^YPPPP55PPY?P?^J7.~7:                       7B7~!!^           JY                                                                  
GGGGGGGBBBBBBBBGGPPGB##BY!.            .........                               .?~^:                                :JY^              ?J:::::::::::!!            .             .      :7^!Y!75?P55PPB7?!^^!J5J!.                                      ?B. ^BPPPPPPPPPPPPPGP^ !5PPPPP55PYYP5JJY7^?7..:                    :GY~!!!!:          .5?                                                                 
PPPPGGGGPPPPPPP5PGBB57^.                                                        ??^:    .         ..                  ^5J.             JJ::::::::::!~   ..  ~: ..             ..  ^^ ^7::J~?PJ5P55PPG!J??5BJ:                                         !#: .GGPPPPPPPPPPPGP~.?PPPPPPPPPP55PY?PJ^J5~!?:                    ?G!~!!!!~.          .P7                                                                
GGGGPPPPPPPP5PG#BY~.                                                            ~G^: .::::::......                      7P7             ?J^::::::::~^  .J7:~^  :^  .:        ::  :: .!~^YJ?55YP55PPY7!!7Y5^                                           ~#^  5BPPPPPPPPPPGP~.JPPPPPPPPPP55P5YP5JYPJ~~~ .~:            :.  :GJ~~!!!!~:           :P!                                                               
PPPPPPPPPP55GB5!.                                                               .B?..^^^^^^^^^^^:.                       .J5^            JY~:::::::~^ !?5~:?~.^7. ..:  .^.  ::  .~::?7~JY!YYJP5PPPY^:7G&Y.                                            ^#~  ?#PPPPPPPPPGP7.JPPPPPPPPPPPPPP5PP5?PY~!7~!YJ:..         .:  :YG!~!!!!!!^            ^G!                                                              
PPPPPPPYJYPP?:                                                                   5G.:^^^^^^^^^^^^^:                        ^5?          .:~Y7::::::^: :5J!JY~^7!. ~7. :^:  .~: ~?^:?7:?Y!555PP5PPP~:JB#J                                              ^#~  7#PPPPPPPPGPJ.?PPPPPPPPPPPPPPP5P5YP5?J55!?5~^?^        .!: !!GY~!!!!!!!~.     .      !B!                                                             
PPPP5?7YPY~.                                                                     !&!:^^^^^^^^^^^^^^^.                       .JG?^:         .?J~::::::  JY?5J:75!^!?~..~!: ~?^:^?~:7Y~Y5J5P55P5PPB7:?BBY                                .  .           ^#~  ~#PPPPPPPGP5:7GPPPPPPPPPPPPPPPPPPPP5YPP?YPJJ?.        .?!:~77B7~!!!!!!!!:     .      .7G~                                                            
PPJ!7Y57.                                                                        .BG^^^^^^^^^^^^^^^^^:.                       ^G5~!!^.       ^JJ~::::. :75P?J55!^JJ^:?Y!^!J!:^Y7~Y5?J5YJP55PPPPBJ:!GGP.                               .   ^: ~^..     ^#~  ^#PPPPPPPPP~~PPPPPPPPPPPPPPPPPPPPPP5PP55PPJ!:.     .~~?Y:~Y!?G!~!!!!!!!!^     ..      ^?G!                                                           
7^75Y~                                                                            7@7^^^^^^^^^^^^^^:^^^.                       .Y5::!~..       ~J?~:::  !PPJYPJ!5PJ7?5?^!5J~?5Y?JPJ?PYYP5PPPPPGJ:^P5P~                                :. ^^ .!^^J7^.  ^#~  ^#PPPPPPPP?:5PPPPPPPPPPPPPPPPPPPPPPPPP55PYJ?7:  .~?J~YP??55!JP~!!!!!!!!!~.    .:      :~7G!                                                          
75Y^                                                                              .BB^^^^^^^^^^^^^^^^^^^:.                       JG!::.:~~:      ~J?^:.  755P5Y5PP??P57JP5JJ55?JPYYP55PPPPPPPG5::JGPY.                           .:  ^. .^:.?7^7Y^7Y: ~#^  ^#PPPPPPP5^JGPPPPPPPPPPPPPPPPPPPPPPPP5PP55P5~.~7?PPY5P5?YP??GY~~!!!!!!!!~:     ^.     .~~7G!                                                         
?:                                                                                 7@J^^^^^^^^^^^^^^^^^^^^.                       !B?^^. ^7?^      ~?7~^. ?PP5YPPYYPP5Y5PYJPPJ5P55PP5PPPPPPPPG~:~GPP7            :. ..       :  .:  .^..7!:~J:^5??PPY??#^  ^#PPPPPPP7!GPPPPPPPPPPPPPPPPPPPPPPPPPPPP55Y7?5PPPP5YPPJ5P55PPGP7~!!!!!!!!^     ^:      ^!~7G7                                                        
                                                                                    G#~^^^^^^^^^^^^^^^^^^:^:                       ~BJ^:   ^JJ^      ^7??: 7P5PPP5PPPY5P55PP55PP5PPPPPPPPPPPBJ::?PPP~       .!. :.  :: .~. .:   :: :?^.~!.:J7!55?YPJ5PG#:  ~&PPPPPPY~5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP55PPPP5PP5PP5PPP55PPJ?57~!!!!!!!^     :^      :!!~7G?                                                       
                                                                                    ~@J^~77!~^^^^^^^^^^^^^^^^.                      ^BJ::.   ^YJ^      ^7?^ ~5PP5PPP5PPPPPPP5PP5PPPPPPPPPPPPP^:^J5PG^    !!:~^ .!: ~~ .::  ^!..!~..~^ ^J!~YY!?P7JP55PP#G   7&PPPPPP7JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5PPPPPPG^.^Y!~!!!!!!~.    .~.     .!!!~!GJ                                                      
                                                                                     5#7Y#J7?J!~^^^^^^^^^^^^^^:....                  ^B?^^^.   ~YJ.      .^^ :JPPPPPPPPPPPPPPPPPPPPPPPPPPPPG7::7Y5P#~  .7Y:~Y~^?!.:!: ~?^.!!..^!:.7Y~!YJ^75~?PY5PP55P5&J   Y#PPPPP5JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPBJ:. ^Y!!!!!!!~.    .~^     .~!!!~!PJ                                                     
                                                                                     :#P!G!^^^~~^^^^^^^^^^^^^^^:                      ^B7^^^.    !57       .:..~YPPPPPPPPPPPPPPPPPPPPPPPPPGY::^5PPP&7  !PJ?YY^!Y^:J?:~?~.^?~:7Y7~7Y!:?Y~JPYY5PY5P5PP5G&~   P#PPPPP5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG5JJYPPPPPPPPPPPPPPPB5:::  YJ~!!!!!~.     ^~.    .~!!!!~!PY.                                                   
                                                                                      ?&7P!^^::^^^~7~^^^^^^^^^^^^.                     ~B!^^^:    .J5^       .~^.~YPPPPPPPPPPPPPPPPPPPPPPPP!::7PPPPBP .YP?JP77PY7?5!:JJ^75J!!Y?:!P?75PYJ55J5PYPP5PPP5BG.  .BGPPPPPPPPPG57!!J5PPPPPPPPPPPPPPPPPPGGY^:!.~YPPPPPPPPPPPPP5^:::. !P!!!!!!~.     :!:     ^!!!!!~~5P:                                                  
                                                                                       GP5?^^^^^^^^~77!^^^^^^^^^^^.                     7B~^^^.     ^5J.       ~?!.^?5PPPPPPPPPPPPPPPPPPPPJ^::JPPPPPB! YYYP5Y5P?7PY7YPJ7J5!!P5?YP5JJPY?5PYPP5PPP5PPPP&J   ~&PPPPPPPPGP?^:~^ ~5PPPPPPPPPPPPPPPPPJ~:::~^  ~YGPPPPPPPPPP~::::: ^G!~!!!!~:     .~^     ^!!!!!!~~JP^                                                 
                                                                                       ^#J?^^^^^^^^^^~7?!^^^^^^^^^^.                     JP^^^^^.     75~       .!?!::~?YPPPPPPPPPPGGPPPP5!::^YPPPPPPG^!PPP5YP5YPPYJ557YPYJ5PYJ5PJYP5YPP55PP5PPPPPPPG&~   Y#PPPPPPBG?^:::~^  :5GPPPPPPPPPPPPPJ~::::::^.   ~5GPPPPPPG?::::::..G7~!!!!~:      ~~.    ^!!!!!!!!~?G!                                                
                                                                                        ?G~^^^^^^^^^:.^~??~^^^^^^^^^.                     PY^^^^^      :5J.        ^!7!~~!?Y5PPPPPGPPPPPPY^::~5PPPPPPPP!YPP5PP55P5YPPY5PPYYP5YPP5PPP55PP5PPPPPPPPPPPBB.  :BGPPPPBBJ^:::::^^   .5GPPPPPPPPPPY!::::::::::    .7GGPPPPP^:::::::~P!~!!!!~:      :!:    ^!~!!!!!!!~7P?                                               
                                                                                         PY^^^^^^^^^^.:^^7J!^^^^^^^^^. ..       .....:::..^B?^^^^.       ?P^          .^~~~~~5#GPPPPPPPPPJ:::!PPPPPPPPP5YPPPPP5PP5PPP5PP55PP5PPP5PP5PPPPPPPPPPPPPPPP&?   7#PPPG#5~:::::::^.    .PGPPPPPPPP?^:::::::::::.     ^5GPPB?:::::::~?!!!!!!!~:      .~^    ^!~~!!!!!!!~!5Y.                                             
                                                                                         ~B!^^^^^^^^^:.^^^~J?^^^^^^^^^.   ..:^^^~~~~^^^::::?B^^^^^^:      ~P7               !G5PPPPPPPPPP7:::7PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#G.  .GG5PBG7::::::::::.     :GGPPPPG5~::::::::::::::      .?GGB~:::::^7?!~!!!!!!!:       ^~.   ^!~^~!!!!!!!~~Y5:                                            
                                                                                          JP^^^^^^^^^^.:^^^^?J~^^^^^^^..:~~~^::..          .!^^^^^^^:      .PJ             .P!JPPPPPPPPPP~:::?5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG#^   J#PG#Y^:::::::::::.      ^BGPPBY::::::::::::::::        ^YY:::::!Y?!!!!!!!!!!~.      .~:   :!!~~!!!!!!!!~~?5~                                           
                                                                                          .PJ^^^^^^^^^^.^^^^^7J~^^^^^^~~~^.                 .P7^^^^^.        YY            75:5PPPPPPPPPP^:::JY5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP&Y   :#GBG!:::::::::::::        ~BGGY^::::::::::::::::          .::^75Y7~!!!!!!!!!!!^       ^^   .~!~^~!!!!!!!!~~!5!                                          
                                                                                           ^G!^^^^^^^^^:.^^^^^!Y!^^^~~^.                     !B~^^^^.         Y5.          57^5PPPPPPPPPP:::^JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB#^   5BGY^::::::::::::^:         :5J::::::::::::::::::.        .:!JJ?!~~!!!!!!!!!!!!!:      :~.   ~!!~~!!!!!!!!!!~~57                                         
                                                                                            75^^^^^^^^^^.:^^:^^!Y!^~~.                        55^^^^^^^:       JY         .G^!PPPPPPPPPP5..:^5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGPG&?   ?#G7:::::::::::::::.          :^^^^^^^^^^:::::::::    ..:^~??7!~~~!!!!!!!!!!!!!!!~.      ^^   :!!~^~!!!!!!!!!!~^5?                                        
                                                                                             YJ^^^^^^^^^:.^^^^^^~J!~.                         :B!^^^^^^:        YY        :G^JPPPPPPPPPG5..:~GPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGBBBBBBBBBGGGGGGPPPP#G. .!B5~:::::::::::::::^::~!77?JYY5PPPPGGGGGGGPP5YYJ???7?JJ?7P?!!~~~!!!!!!!!!!!!!!!!!!!^      :~.  .~!!^^~!!!!!!!!!!~:YJ                                       
                                                                                             :G!^^^^^^^^^::^^^^^^~7.   ..                      ?P^^^^^^^^.       5J       ^G~5PPPPPPPPPG5..:~GPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB&~ :~5?^::::::::::^^!!!YPPGGGGGGGGPPPPPPPPPPPPPPPPPGGPPP?::. .G!~!~^~!!!!!!!!!!!!!!!!!!!~:      ^:   ~!!~:~!!!!!!!!!!!^.JY                                      
                                                                                              ?P^^^^^^^^^:.:^^^^^^^^...                        .G7^^^^^^^...      5?      ^G!PPPPPPPPPPG5..:7G5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG&J.:^7^:::::::^!?JJJP577PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY.   ~P~~!~:~!!!!!!!!!!!!!!!!!!!!~.     :^.  :!!~::~!!!!!!!!!!!^ JY                                     
                                                                                              .BJ^^^^^^^^^:.^^^^^^^~^                           !P^^^^^^^^...     .P~     ^G?PPPPPPPPPPG5..:?B55PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#P::^^^::::^!JPPY?7?J7~~!Y5PPPPPPPPPPPPPPPPPPPPPP5PPPPPPPPP!   ?Y~~!~:~!!!!!!!!!!!!!!!!!!!!!:      ^:  .~!!^.^!!!!!!!!!!!~: JY                                    
                                                                                               J&~^^^^^^^^^.:^^^^^^^~.                           57^^^^^^^:..      ~P:    .5YPPPPPPPPPPG5..:?GPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGG~^~^:::~?5P5J~.^Y?!~~!~!?~5PPPPPPPPPPPPPPPPPPPP55PPPPPPPPPY.  5?~~!~.~!!!!!!!!!!!!!!!!!!!!!~.     .^   ^!!~..~!!!!!!!!!!!~: JY.                                  
                                                                                               ^&P^^^^^^:^^:.^^^^^^^^^                           ^Y^^:.:^^^^:..     7J     75PPPPPPPPPPGP..:YGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG!~!:^!YG##P^   !J!~~!!!!!J.!PPPPPPPPPPPPPPPPPPPP5PPPPPPPPPP5: .P!~~!^.~!!!!!!!!!!!!!!!!!!!!!!^      :.  :!!!^.:!!!!!!!!!!!!~. JY.                                 
                                                                                                Y@?^^^^^^:^^:.^^^^^^^^:                           ?!^: :^^^^^^:.    .Y:    ?5PPPPPPPPPPPP..^YYYPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP7!7J5B#BGPP7   !J!~!!!!!!!?. 7PPPPPPPPPPPPPPPPPPPYPPPPPPPPPPP7 ^P~!~!^.~!!!!!!!!!!!!!!!!!!!!!!~.     .:  .~!!~..~!!!!!!!!!!!!^. JY                                 
                                                                                                :#&!^^^^^^^^^.:^^:^^^^^.                          :?^^::^^^^^^^:     !!    ?GPPPPPPPPPPGP. ^5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPBJ5GPPBGPPPPY.  !7!~!!!!!!!!!. .5PPPPPPPPPPPPPPPPPYJPPPPPPPPPPP5.7Y~!!!:.~!!!!!!!!!!!!!!!!!!!!!!!^      :. .~!!!: :~!!!!!!!!!!!!^  YJ                                
                                                                                                 !@P^^^^^^:^^:.^^^^^^^^^.                     ..   !!^: .^^^^^^^:.   .7    7BPPPPPPPPPPGP. ^PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPB###P?JPPPPP5^ .7~~!!!!!!!!!!!. .5PPPPPPPPPPPPPPPPG?YPPPPPPPPPPPP~?J~!!!:.~!!!!!!!!!!!!!!!!!!!!!!!~.     ..  ^!!!~. ^!!!!!!!!!!!!~. .P!                               
                                                                                                  Y@?^^^^^^:^^::^^:^^^^~:                          :!^^:.:^^^^^^^:    ^:   ~&PPPPPPPPPPGG~ :5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGBGP5?7PPPPPP~ :7:.~!!!!!!!!!~!^ .5PPPPPPPPPPPPPPPP5!5PPPPPPPPPPPP7Y?~!!~..~!!!!!!!!!!!~~!~!!!!!!!!!^      .. :!!!~: .~!!!!!!!!!!!!^. :P^                              
                                                                                                  .B#~^^^^^::^^.:^^:^^^!~. .                       .^~^^^^^:^^^^^^:   .^   ^#GPPPPPPP5J?5~ .~^!?JY5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5?5PPPPP! ^!. :!!!!!!!!!!~!^ .5PPPPPPPPPPPPPPPGJ7PPPPPPPPPPPPPJY7~!!~..~!!!!!!!!!!!~~!~!!!!!!!!!~.      . :~!!!^  ^!!!!!!!!!!!!!:  !P:                             
                                                                                                   !@5^^^^^^:^^::^^:^^^~J^.                         :5~^^^^^^^^^^^^    :.  :#GPPPP57^:~7^ .!!!?JY5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJYPPPPP! ~!.  ^!!!!!!!!!!!!^ .5PPPPPPPPPPPPPPPP!YPPPPPPPPPPPPPY5!~!!~ .~!!!!!!!!!!!~~!!~7!!!!!!!!:      ...~!~!~. .~!!!!!!!!!!!!~.  ?5                             
                                                                                                    Y@?^^^^^^:^^::^^:^^^77:                          J?^^^^::^^^^^^:   .^  .B#PPPP5?J5J: ^5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPJ7PPPP5~ ~~   .~!!!!!!!!!!!!! .YPPPPPPPPPPPPPPPJ7PPPPPPPPPPPPPP55!~!!^ .~!!!!!!!!!!!!~~!~!7~!!~!!!~.      ..~!!!!:  ^!!!!!!!!!!!!!^  .57                            
                                                                                                    .##~^^^^^::^^:^^::^^^7~:                         ^5^^^^:.:^^^^^:    ^.  B&PPPPP5Y!  ~YPPPPPPPPPPPP555PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5?5PPP?:.!^    .!!!!!!!!!!!!~!: JPPPPPPPPPPPPPPP~YPPPPPPPPPPPPPP5Y7~!!: :~!!!!!!!!!!!!~^~~^?!!!!!!!~:      .:~!!!!~. .~!!!!!!!!!!!!~:  ^G:                           
                                                                                                     !@5^^~^^^::^::^^:^^^~?^:                        .Y7^^^^..^^^^^.    :7 !#BG5J!^!...!J.!JYYYYJJ?7!!?J5P55YJ777YPPPPPPPPPPPPPPPPPPPPPPPP5?JPPJ^ :!:     :!!!~!!!!!!!!~~~ ?PPPPPPPPPPPPPP?!PPPPPPPPPPPPPPPY?7~!~: :~!!!!!!!!!!!!~:^!^7?~!!!!!!^       :^!!!!~:  ^!!!!!!!!!!!!!~.  ?5                           
                                                                                                      Y@?^^~^^^:^^::^::^^^Y?^.                       .!5^^^^^^^^^^:.     J~BGY!.  .~:::~J^      .^!7???!~^:.     .!5PPPPPPPPPPPPPPPPPPPPPP5?Y?^ .~~.      ^!!~~!!!!!!!!!~!.~PPPPPPPPPPPPP5^YPPPPPPPPPPPPPPP5~~!!~. :~!!!!!!!!!!!!~:.~~!Y!~!!!!!~.      .^!!!!!^  .~!!!!!!!!!!!!~:  .57                          
                                                                                                      .##~^~~^^::^^:^^:^^^!5~^.                      .^Y!^^^^^:^^^^.     ^#BP?.    .^:::~?:.:~!??7~:.              ^YPPPPPPPPPPPPP555YJJJ5P5J~~.^P:       ^!!~~!!!!!!!!!~^^:5PPPPPPPPPPPP7~PPPPPPPPPPPPPPPPPJ:~!^  :~!!!!!!!!!!!!!^.:~~J?~!!!!!~:      .:~!!!!~.  ^!!!!!!!!!!!!!~.  ^G:                         
                                                                                                       !@5^^~~^^::^::^^:^^^J?^^.                     :^7Y^^^^^^^^^^^:    .BGPP5J????J!::^?Y55?~:                    :JPPPPP55YJ?!~^^!?JY5PPPP5?J:~?       ~!!~~!!!!!!!!!~:!:YPPPPPPPPPPPY^JPPPPPPPPPPPPPPPPPP~^!^  :~~!~~!!!!!!!!!^ .~~7Y!!!!!!!^       :~!!!!!:  .~!!!!!!!!!!!!~:   Y?                         
                                                                                                        Y@7^^~^^^.^^:^^::^^~Y~^^.                   .^^^Y~^^^^:^^^^:.     J#PPPPPPPPP5~:~5PP~                        .7?7!~^:..:^!J55PPPPPPPPPJJY:7      .~!!~~!!!!!!!!!~.^~7PPPPPPPPPPP7~5PPPPPPPPPPPPPPPPPP?^~:  :^~~~~!!!!!!!!!^  ^!!Y?~!!!!!^       .~!!!!!^   ^!!!!!!!!!!!!!^   ^G:                        
                                                                                                        :##~^~~^^:.^^:^^:^^^?7^^^.                  :^^^?J^^^^::^^^^.     ^#PPPPPPPPG5^:7PPY.                          ...   :!J5PPPPPPPPPPPPP575JJ.     .~!~~~!!!!!!!!!~..~75PPPPPPPPPP~?PPPPPPPPPPPPPPPPPPPY~^.  .^~~^~!!!!!!!!!^  :!~?Y!!!!!!!.      .~!!!!!~.  :!!!!!!!!!!!!!~.   Y?                        
                                                                                                         !@5^^!~^^..^::^::^^~J~^^^.               .:^^^^~5~^^^:.:^^^:     .GBPPPPPPPB?::YPP?                    ..      .:^!J5PPPPPPPPPPPPPPPPP??P5!:    .~!~~~!!!!!!!!!!: :!YPPPPPPPPP5~JPPPPPPPPPPPPPPPPPPP5!.   .^~~:~!!!!!!!!!^  :!!!57~!!!~77      .~!!!!!~.  .~!!!!!!!!!!!!~:   ~G.                       
                                                                                                          5@7^~!^^^.:^:^^:^^^?7^^^^.             :^^^^^^:J?^^^^^^^^^:      ?&PPPPPPG#~:^5PP7                      .:^!7?JYPPPPPPPPPPPPPPPPPPPPPJ?B!^J7!^..~!~^~!~!!!!!!!!: .~75PPPPPPPP5~5PPPPPPPPPPPPPPPPPPP5!    .~~^.~!!!!!!!!!^  .~!~YY~!!!!~YY     .^!!!!!!:   ^!!!!!!!!!!!!!^    P!                       
                                                                                                          :#B^^~!^^:.^^:^::^^~J~^^^^:..       .:^^^^^^^^^^5^^^^^^^^^:      .BGPPPPPBP::~GPP!               ..:~!?JJJ?7!^::JPPPPPPPPPPPPPPPPPPPP55P!:..^!?JJ7~^~!~!!!!!!!!^  :!?PPPPPPPPY7PPPPPPPPPPPPPPPPPPPPP^    .^:..~!!!!!!!!!^  .~!~?5!!!!!~~BJ     ^!!!!!!^   .~!!!!!!!!!!!!^    ?Y                       
                                                                                                   .:~!7?J?J@J^^!~^^..^:^^::^^?J^^^^^^^^^^^::^^^^^^^^^^^^:5?^^^^^^^^.       ?&PPPPP#J::!GPP~           .:^~!!!~~^:.       :YPPPPPPPPPPPPPPP5Y5PP55P5YJ7~:^75P?!~~~!!!!!!!!: .~!YPPPPPPPYJPPPPPPPPPPPPPPPPPPPG5.    .^  .!!!!!!!!!!^  .~!~7G?~!!!!^Y&^    ^!!!!!!~.  .~!~!!!!!!!!!!~.   ~B:                      
                                                                                              .^~7???7!^:.  5&!^~7~^^ :^:^:.^^!G!^^^^^^^^^^^^^^^^^^^^^^^^:?G^^^:^^^^.       ^&GPPPPB!::?GPP~            ..                 ^5PPPPPPPPPPP5YJJYPPPPP5555GPPY?!?PBJ~^~~!!!!!!~. :~7BGPPPPPYYPPPPPPPPPPPPPPPPPPPBY     :^  :!!!!!!!!!!:  .~!~!B5~!!!!~!@P    ^!!!!!!~.   ^!!!!!!!!!!!!~.   ^&~                      
                                                                                           ..:^::..         :&G^^!7^^: :^:^::^^YY^^^^^^^^^^^^^^^^^^^^^^^^^^B7^^^^^^^.        5#PPPGG^:^5PP5^                                !PPPPPPPPPY!~?5PPPPPPP5GP?JYJJ??7!?GGJ7!~~!!!!!^ .~~?GPPPPP5YPPPPPPPPPPPPPPPPPPPB7     ^^  ^!!!!!!!!!~:  .~!!~PG~!!!~~:G&^   ^!!!!!!~.   ^!!!!!!!!!!!!~.   .#7                      
                                                                                   .....                     ?@J^^7!^^. ^:^^.^^~P!^^^^^^^^^^^^^^^^^^^^^^^^:JP^^^^^^^:.       ~&PPPBY::~PPP5:                                :5PPPPP5J^.~JPPPPPPPGPY7:        . .!?Y5Y7~~~!!!: :!~5GPPPP55PPPPPPPPPPPPPPPPPPP#~     ^^ .~!!!!!!!!!~.  .~!!~5B~~!!~~.?@J   ^!!!!!!~.   ^!!!!!!!!!!!!~.   .BJ                      
                                                                              .:~!~^:.                        5&~^~?~^^ .^:^::^^JY^^^^^^^^^^^^^^^^^^^^^^^^^^B!^:..:^^:        GBP5P7::?GPPY.                              :7YPPPP57:.^JPPPPPPPGP?~::::             :!JJ?!~~!~. ~!7PPPPP55PPPPPPPPPPPPPPPPPPGB:    .~^.:~!!!!!!!!!~.  :~!!~YB~~!!~~.^&G.  ^!!!!!!~.   :!!!!!!!!!!!!~.   .GJ                      
                                                                          .^7JJ7~.                            :#P^^!?^^: ::^^.:^~P!^^^^^^^^^^^^^^^^^^^^^^^^.55^^::^^^^        ?&J~5!:^5PPPY.                           .^?JY5PP57. ~JPPPPPPPGP7^::::~?J?~~^:.  .      ^JYJ!~!^ :!!YPPPPP5PPPPPPPPPPPPPPPPPPBP     :!^.^!!!!!!!!!!^   :!!!~J#!~!!!~..G&^  ^!!!!!!~.   :!!!!!!!!!!!!~.   .BJ                      
                                                                      .~7JYJ!^                                 !@7:^J!^^. ::^:.^:J5^^^^^^^^^^^^^^^^^^^^^^^^:~B~^: :^^.        ^#!^5~:^PPPPY.                         .^~^:^JPY!. ~YPPPPPPPPP?^:::~?55J7!!!7?JJJYY!~^.   .75Y7!: ^~?PPPPPPPPPPPPPPPPPPPPPPPP&?     ^!^:~!!!!!!!!!!:   ^!!!~?#!^!!~~. Y@7  ^!!!!!!~    :!!!!!!!!!!!!~.   .B?                      
                                                                   :~77!^.                                      P#^^!Y~^^  ::^.:.^P7^^^^^^^^^^^^^^^^^^^^^^^^:PJ^^::^^::       .PY!G7::?GPPY.                        ::.  !Y5!.  JPPPPPPPPP?^::^!Y5Y7~~~~~~~~~!7?P&#BBP7:  .!JY7..~7PPPPPPPPPPPPPPPPPPPPPPPG#:    .~!~~!!!!!!!!!!~.  .~!!!~?#!^!!~^. !@5  :~!!!!!^    :!!!!!!!!!!!!~.   .#7                      
                                                              .^7JJ7~.                                      ....!&5:^7J^^: .:^:.. ?5^^^^^^^^^^^^^^^^^^^^^^^^:!G^^^^^^^^.       ?&57?7:^5PP5:                          .~JJ!.   ~5PPPPPPPJ^::^?55?!~~~~~~~~~~~~~~~7PBGGBGJ!:  ~Y7.^!YPPPPPPPPPPPPPPPPPPPPPP#5     :!!~~!!!!!!!!!!~.  .~!!!~J#~:!!!^. ^&G. .~!!!!!^    ^!!!!!!!!!!!!~.   :#!                      
                                                           ^?Y5Y7^.                               ...:::^^~~~~~~^J@7:^J7^^. .:^...:P7^^^^^^^^^^^^^^^^^^^^^^^^.G?^^^^^:^:       ^#J~!Y~:~PPP~                        :~7!:     !5PPPPPP5!::^?PY7~~~~~~~~~~~~~~~~~~~~JBBPPGGP?^.:77^~YPPPPPPPPPPPPPPPPPPPPPP#?.    ^!!~!!!!!!!!!!!^   :!!!!~Y#^:!!~:. :##: .~!!!!!:    ^!!!!!!!!!!!!^    ~#~                      
                                                        .7P5?^.                        ...:::^^^~~~!!!~~^^::..... 5#^:~5!^:  :^^.: 75^^^^^^^^^^^^^^^^^^^^^^^^.?G^^^^^::^.       PP~~?P^:7GPJ                     .^!!^.     .7PPPPPP57^:^?5Y7~~~~~~~~~~~~~~~~~~~~~~~!5#GPPPG5!::~?!JPPPPPPPPPPPPPPPPPPPPPGP7:   .~!!~!!!!!!!!!!~:   ^!!!!~YB^:!!~.  .G&^ .~!!!!~.   .~!!!!!!!!!!!!^    7#.                      
                                                       ~GP~                  ..:::^^^~~~~~!!!!!!!~^::.            .BP:^?Y^^:  :^:.:.P7^^^^^^^^^^^^^^^^^^^^^^^^:B7^^^^^:^:       !#7~~Y5^:JB5:                  .^^:.       :JPPPPY7~^::75Y!~~!!?JJ??77!!!!!!!!~~~~~~~~?G#GPPP5?!^7J?PPPPPPPPPPPPPPPPPPPPPG57^   :~~!!!!!!!!!!!!~.  .~!!!!~5G::!!^.   P&~ .~!!!!~.   .~!!!!!!!!!!!~.    5P                       
                                                      ~&Y                 .:~~~!!!!!!!!!!~~~~~^:.                  ~&?:^Y?^^. .:^.:.!5^^^^^^^^^^^^^^^^^^^^^^^^.JP^^^^^:^:       .GY~~!PY:^5G7           .^!:   ..         !5PP5J!^:::!YY!~~!!!777!!!!!!~^^^^^^~~~~~~~~~!Y#BPPPP55P#55PPPPPPPPPPPPPPPPPPPPPPJ7~. :~~~!!!!!!!!!!!^   ^!!!!!~GP.:!!^    5@! .~!!!!~    :!!!!!!!!!!!!~.   .B?                       
                                                      5&:             .:^~!!!~~~~~~~~~~~~~~~^.                      J&~:~57^:  .^:.^:57^^^^^^^^^^^^^^^^^^^^^^^:^B!^^^^^^:.       ?B!~~!BJ:^PG~         ~!^?GJ~.         ^JPP5?~:::^~J57~~~!!~~^::::::::::::..::::~~~!!!~~7G#GPPPPPB#PPPPPPPGGPPPPPPPPPPPPPPP?~7~:~!!!!!!!!!!!!~.  .~!!!!~!B5.^!!:    5@~ :~!!!!^    ^!!!!!!!!!!!!^    !#^                       
                                                      GB            :^~~!!~~~~~~~~~~~~~~!~:.                        .GG:^?P~^.  .^.::!5^^^^^^^^^^^^^^^^^^^^^^^^.5Y^^^^^^^:       :B?~~~7B7:~GP^      ^?7. .5#PY^      ^JPPY7^::~7?7!?7!!7!!!~~^^::::::^^^~~~~~~~~~~~~!!!!~!5#GPPPPPGGPPPPPP5YGGPPPPPPPPPPPPPP7.!?!~!~!!!!!!!!!^   :~!!!!~!BJ ^!~.   .G&^ :!!~!~.   .~!!!!!!!!!!!~:    YG                        
                                                     .BG          .^~!!!!~!!~~~~~~~~~~!~^.                           ^&J.^YY^^   ::.^^Y!^^^^^^^^^^^^^^^^^^^^^^^:~B~^^^^^^^:       JP~~~~?B!:~G5^    !J~.   ^BBP5!  .~JPPJ~::^!JY?!!~^^^::.    ............::^~~~~~~~~~~!7?!~?BGPPPPPGPPPPPP5:^?J5GGPPPPPPPPPPPJ.^Y7~~~~!!!!!!~.  .~!!!!!~!#7 ~!~.   .B#: ^!!!!^    :!!!!!!!!!!!!^.   :B?                        
                                                      G#.        :~!!~7!!~~~~~~~~~~~~~~:                              ?&^:~P7^:   :..^75^^^^^^^^^^^^^^^^^^^^^^^^.PJ^^^^^^^:       :G7~~~~J#!:~GP!..?J^:.    ?&GPP77YP5?^::~?YJ!^:..    ..:^^~~~~~~~~~~~!!!~~~~!!!!!~~~~~~?P?~!GGPPPPBPPPPPPG7  .^!JPGPPPPPPPPPPJ..J?~~!!!!!!!^   :!!!!!!~?#! ~!^    :#B. ^!!!!:    ^!!!!!!!!!!!~:    JB.                        
                                                      ~&?      .~!~!~^~~~~~~~~~~~~~~~~.                               .GG.^?G~^.  .:.:^Y7^^^^^^^^^^^^^^^^^^^^^^^.!G^^^^^^^:        J5~~~~~Y#7:~PG55J:::     :B#PPPY?~::~7JJ!:.     ..::::::...       ...:^^~!!!~!!!!!~~~~~?B?^7BPPPP#GPPPPPG5.  .::^!J5PPPPPPPPPY..J?~!!!!!!~.   ^!!!!!!~J#^ ~!:    :#G..~!!!~.   .~!!!!!!!!!!!~.   :#7                         
                                                       YG     :~!~~!^^!~~~~~~~~~~~~~!^                                 ~&?.^5Y^:   .:.^75^^^^^^^^^^^^^^^^^^^^^^^^.G7^^^^^^..       ^B7~~~~~JB?:^5B5^:::      JG?!^:^~!77!:                                 .:^~~!~~~~~~~~~~YB7^JBPP5#GPPPPPGG^ .!7!~^::^7YPPPPPPPJ..J?~!!!!!:   .~!!!!!!~5G..~~.    ^&P .~!!!^    ^!!!!!!!!!!!~:    5P                          
                                                       ^&~   .~~~~~~:^~~~~~~~~~~~~~~~:                                  Y#^:!B7^:   :.:^Y7^^^^^^^^^^^^^^^^^^^^^^^.?P^^^^^^^^.       55~~~~~~7B5^:?!:::.   .:::^^~!77!~:.                                       .^~!~~~~~~~~!GP~:PGPPBPPPPPPB7^.?7~!7???7~^~7Y5PPPP? .J?!~!!~.   ^!!!!!!!~P5 ^!~.    !@J :!!!~.   .~!!!!!!!!!!!~    7#^                          
                                                        GP   :!~~~~!^^~~~~~~~~~~~~~~~:                                  :#5.^JG~^.  ...:75:^^^^^^^^^^^^^^^^^^^^^^::G!^^^^^^^:       !#!~~~~~~!PG?::::: ..::^!7??7!^:.                                            .:~!~~~~~~~?#?:?GPBBPPPPPG5::??::::::J5??7~^^!J5PP! .??7~!:   .~!!!!!!~!BJ ~!^     ?@7 ^!!!^    :!!!!!!!!!!!~:   ^#7                           
                                                        ^&7  ~!~~~~!~^~~~~~~~~~~~~~~~^                                   7&~.^G5^:   ...^Y7:^^^^^^^^^^^^^^^^^^^^^^.J5^^^^^^^^.      .BY~~!!!!!~?GP7^:::^~7?J?7!^:.                      .                     .    .^~!~~~!?7PP^:5P#PPPPPPB!:!J^::::::YJ!7?JY7^:^!?Y: .77J~    :!!!!!!!~7#~.~!:     Y@~ ~!!~.   .~!!!!!!!!!!!^   .G5                            
                                                         ?&^ ~~~~~~~!~~~~~~~~~~~~~!!!!^.                                  PG.:!#7^.   . :!5^^^^^^^^^^^^^^^^^^^^^^^::B~^^^^^^^:       ?B!!!^. .:~~?PY~^~777!~^:.                 .  ......                     ..::.  .^!~~~?BB&! !PGPPPPPB5:^Y!::::::^5!:^^~7J?!~::^!!^^^~J~   ^!!!!!!!~YB:^!~.     P&^.~!!^    ^!!!!!!!!!!!~.   YB.                            
                                                          5B.~~~~~~~~!!~~~~~~~~!J555555?^:.                               ^&?.^YB~.     .^Y?:^^^^^^^^^^^^^^^^^^^^^^.5Y^^^^^^^^.      :#!.      ^!~~!!!!!~^:.               ......                                ..:...^~~~~?#@5 :PPPPPPPB!:?J:::::::!P~:::::^7?7!^: .^!?^.!? .~!!!!!!!~P5.~!^     .BB.:!!~.   .~!!!!!!!!!!~:   7#^                             
                                                          .PP^~~~~~~~~!!~~~~~~!7?7!~~~!!!!!!~^^::.                         J&^:~G5.      :!5^^^^^^^^^^^^^^^^^^^^^^^.~B~^^^^^^^:       55       ^!~~~!~^:.                                   .....                   ..:~!~~~~7B@!^BPPPPPB5:^5~:::::::75^:::::::~JYYJ!:  .~ ^! ^!!!!!!!~!B7.!!:     :&P ^!!^    ^!!!!!!!!!!!^   ~#!                              
                                                           .5P~~~~~~~~~!!!~~~~!~~~~~~~~~~~~!!!7?JJJ?!~^..             ..:^~7#G.:7&!       ^Y?:^^^^^^^^^^^^^^^^^^^^^^.PJ^^^^^^^^.      ~#:     :~~!7!^.                           ..::^^~~~!!!!~~~~~~~~~~^::..          .^~~~~~7#&P#PPPPPB!:?J::::::::7Y::::::::::^~7PY!^. ^~  ~!!!!!!!~!B^^!~.     ~@J.~!~.   .~!!!!!!!!!!~.  :#?                               
                                                             J57~~~~~~~~~!!!!~~~~~~~~~~~~~~~~~~~~!7?JY5555YYYJJJ!!!!!!!!7?JJY&7.^YB.      .!5^^^^^^^^^^^^^^^^^^^^^^^.7G^^^^^^^:       .GJ   :^!7?7^   ..                    .:~!!!!!!!!~~~~~^^^^^^^~~!!7???7!~^::.      .^~~~~~J@@#GPPPBY:^Y~::::::::?!:::::::::::::^Y5^:~~  :!!!!!!!!~JP.~!^      7@7:!!^    ^!!!!!!!!!!~:  :GY                                
                                                              !Y?!~~~~~~~~~~~!!~~~~~~~~~~~~~~~~~~~~~~~~~!!!!7!J#Y.....       J#::~B?       :J?:^^^^^^^^^^^^^^^^^^^^^:.G?^^^^^^^.       ?B.:~7??~.  .:^.                .^!??J?7!~^:::..........:::::::::^~!77?J?7~~^:.  .^~~~~~!G@&GBPGG~:??::::::::??::::::::::^^^^::7Y:   .~!!!!!!!!^P?:!~.      Y&~^!~.   :~!!!!!!!!!~:  .G5                                 
                                                               .7Y?~~~~~~~~~~~~!!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!#?           ^@P :7P.      .~5~^^^^^^^^^^^^^^^^^^^^^^.?G^^^^^^^^.      :#?7?!:   :^~~.             .^7?J?7~:..                     ....::::::^~!???7~~^:  :~!~~~J#@BG&P!:^Y~::::::^??:::::::::::~JJYYJ?JP~  :!!!!!!!!~^G^^!^      .GB:~!:   .~!!!!!!!!!!^  .PP.                                 
                                                                 ^5Y~~~~~~~~~~~~!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ !&7          J@@7 .?^       :JJ:^^^^^^^^^^^^^^^^^^^^^::B7^^^^^^^:       5Y.   .:~~77.           :~!7!~:.                                 .:::::::^~?J?!~^: .^~~~!Y&&PJ!::~J^:::::~?!::..           .:^!7J5J.~!!!!!!!!.?P:~!:      ^&Y:!^    ^!!!!!!!!!!~. .PP.                                  
                                                                  .J5!~~~~~~~~~~~!!~~~~~~~~~~~~~~~~~~~~~~~~~~:   Y#:        .#G5&^ .^       .~P~:^^^^^^^^^^^^^^^^^^^^^ YP^^^^^^^^.      ~P...^~!~77.        .:^~~^:.                                       .::::::::^7YJ7~^. :~!~!G&!::::J?::::::^^:.                    .#5~!!!!!!!^.P7^!~.      ?@!^~.   .~!!!!!!!!!~. .PP.                                   
                                                                    7P7~~~~~~~~~~~!!!~~~!~~~~~~~~~~~~~~~~~~!^    :&Y        !@5!&G. ^:       :PP:^^^^:^^^^^^^^^^^^^^^^.!&7^^^^^^^:      :G!~~!~~7?.       ^!!~:.                                            .:::::::::^?P57~. :~~~J@Y::^7J5Y7~:::::                .:^!::^BG~~!!!!!~ ~G:~!:      .GB^~:    ^!!!!!!!!!~: :G5.                                    
                                                                     ~P?~~~~~~~~~~~~!!!~~~!~~~~~~~~~~~~~~~~~.     Y#:       J@Y:J@J  :. .     ~#7:^^^^^^^^^^^^^^^^^^^^^.B5^^^^^^^:       Y?~~~~7J.     ^7J7^.                                                .::::::::::^JGY~: ^!~!#P:!7~^^!J5Y7~:         .:^~7?JYYJ7!?~7?7~!!!!!~. YJ:!~.      ^@J^^    :!!!!!!!!!~: ^BY                                      
                                                                      :PY^~!~~~~~~~~~~!!~^~~~~~~~~~~~~~~~~~~.     ^@7       Y@J^^G&^  ....     5G^^^^^^^^^^^^^^^^^^^^^^.7&~^^^^^^:.      ~Y~~~~J^    :YP7:                                                    .:::::::::::~PP!:.~!7PB~~^^^^^^^!?J?~..!??JYY5YYJ?7!~~^  J^.~~!!!!!!: :G^~!^       Y&~~.   .~!!!!!!!!~: ~B?                                       
                                                                       .5P^:~!~~~~~~~~~~!!~^~!~~~~~~~~~~~~!~       BP       5@?^^!&B:  ..:.    ^#?:^^^^^^^^^^^^^^^^^^^^^.#Y^^^^^^^^      .?!~~!?   .JP?:                                                       .::::::::::::YG!::~?G#~^^^^^^^^^^^~~^^!!!!~~^^^::::^^.  J!^!!!!!!!^  JJ:!~.      :#Y^:   .~!!!!!!!!~: ~B?                                        
                                                                         7B7.^!~~~~~~~~~~~!!^~!~~~~~~~~~~~!^       5B.      P@?^^^J@5.  .::.    JB^^^^^^^^^^^^^^^^^^^^^^.J#~^^^^^^^.      !J~~7!  ~B5^                                                          ..:^:::::::::JP!.^~B&!^^^^^^^^^^^^^^^^^^^^^^:^^^^^^:   J7~!!!!!!^  :G^^!^       ?&!^    ^!!!!!!!!!: 7B!                                         
                                                                          ^PY..~!~~~~~~~~~~!!^^~~~~~~~~~~~!^       J#:      5@J^^^^P@7.  :::.   .BJ:^^^^^^^^^^^^^^^^^^^^:^&Y^^^^^^^:.     ~5!~7^ ?#?.                                                           .:::::::::::::J5~:~5&!^^^^^^^^^^^^^^^^^^^:..^^^^^^:   .57~!!!!!^   JY.!~.      .GP^.   :~!!!!!!!~: JB~                                       ...
                                                                           .7Y^ ^~~~~~~~~~~~!7^^~~~~~~~~~~!~       !#:      J@Y^^^^!&B^. .^::    7#^:^^^^^^^^^^^^^^^^^^^^:5#~^^^^^^^:     .?!~!^Y#!                                                              .:::::::::::::JJ:^?&7^^^^^^^^^^^^^^^^^^::^^^^^^^:    !J~!!~!!^  .~G:^!^       !&7.   .~!!!!!!!~:.5P:                                   ........
                                                                             :?!..~!~~~~~~~~~!7~^~~~~~~~~~!~.      !B:      ~@P^^^^^?@Y:. :~^:   .GY:^^^^^^^^^^^^^^^^^^^^:!&?^^^^^^^^      ~~~~PB^                                                               .:::::::::::::^Y!.!&Y^^^^^^^^^^^^::^^^^^^^^^^^^:    ~!~!!!!!:  ::57.!~.       GG:    ^!!!!!!!~::GY.                                ......... ..
                                                                               !J: ^~~~~~~~~~~!7~^~~~~~~~~~!^      ~G.      .B#~^^^^:5@7:. ^~^:   !#^:^^^^^^^^^^^^^^^^^^^^^GB^^^^^^^^.     7P?P5:                                                                ...::::::::::::7J.^BB~^^^^^^^^^^:::^^^^^^^^^^^.  :7JJ~!!!!~:  :.75 ^!:       !&~    :!!!!!!!~.~BJ                             .................
                                                                                ^J^ :~!~~~~~~~~!7~~~~~~~~~~~~.     ~Y        J@?^^^^::#B^:  ~!^:   PY.^^^^^^^^^^^^^^^^^^^^^7&7^^^^^^^:     7@#7                                                                   :::.::::::::::~P^:P@?^^^^^^:^^^^^^^^^^^^^^^: .~?J!.^!!!!~.  :.~P..!^       .GP    :~!!!!!!~:?G!                         ......................
                                                                                 .Y7 .^!~~~~~~~~!7~~~~~~~~~~!~    .J7        :#B^^^^^:!@Y^: .7!^:  ~#~:^^^^^^^^^^^^^^^^^^^^^GP^^^^^^:      :P!                                                                   .. :::.::::^::::PJ.J@5^^^^^^^^^^^^^^^^^^^^:^^7?!:  :!!!!^. .. :P^ ~^        7&^   .~!!!!!!^^5P:                      ..........................
                                                                                  .YJ  ^~~~~~~~~~~!~~~~~~~~~~!^   .P~         ?@?^^^^^.5@7^: :?~^.  5P.^^^^^^^^^^^^^^^^^^^^^?&!^^^^^.      J7                                                                     .:..:::::::::::JG:?@G^^^^^^^^^^^^^^^^^:.:7Y!:    .~!!!^  .. :5~ :~.       .BY    ^!!!!!!^~GJ                    ..............................
                                                                                    J5. :~!~~~~~~~!~~~~~~~~~~~!^  :P:         .B#~^^^^^:#B~^: ~J~^. ^#!.^^^^^^^^^^^^^^^^^^^^~#Y^^^^^^.    7J                                                                    ..  :::.:::^^::::JB~!#G^^^^^^^^^^^^^:..:~7777     .~!!~:     :Y^ .~.        ?#:   :!!!!!~^?G!                 ..................................
                                                                                     7P^ .~!~~~~~~!!^~!~~~~~~~~!^ !P.          ~&5^^^^^:!@Y^^. 7J^^. YG.:^^^^^^^^^^^^^^^^^^^^5B~^^^^^^.  ^5.                                                                      .:..:::.:::::::J#!~BP^^^^^^^^^^:..:~!7!~^~7     ^!!^.     ^J^  ^:        :#7   :~!!!!~!55:             .......................................
                                                                                      ~P! .~!~~~~~~!!:~!~~~~~~~~!~?G:           ?&7^^^^^:5&!^^..JJ^^ :#7.^^^^^^^^^^^^^^^^^^^^7&7^^^^^^.  5!                                                                     .. ..::.:::^^::::Y&!7@J^^^^^^^:. :!JJ7~^^^.!Y    :!~:      ^J:  ::         5P   .~!!!~~JG7          ............................................
                                                                                       :5?  ^!~~~~~~7~:~~~~~~~~~~!7#~            5B^^^^^^:#B^^^.:5?^^ JB.:^^^^^^^^^^^^^^^^^^^~B5^^^^^.  ~Y                                                                        ....:::::^:::::P#~5B~^^^^:  .~?J7~^^^^^!JP7   :!^.      ~7.  .:         !B^  .^!!~~7PY:      .................................................
                                                                                        .YY  ^!~~~~~~7^^~~~~~~~~~~~GY            .PY:^^^^:!@J:^^ ~P7^::B? ^^^^^^^^^^^^^^^^^^^^Y#~^^^^^:.?:                                                                      ......::::::::::7@BYG!^^:. .~7?7~^^^^^~JPBBP.  .~:      .!!    .         :B!   ^!!~!Y5!   ......................................................
                                                                                          Y5  ^~!~~~~!7:^!~~~~~~~~~JG.            .P!^^^^^:Y&!^^: 7G!^:?#:.^^^^^^^^^^^^^^^^^^^!#?^^^^^^7!                                                                       ....:::.:::::::^B@&B!:. .^!7!~^:^^:^75GP7^7?  .:.      :7^            ...5Y   :!~!J57...........................................................
                                                                                           5Y  :~~~~~~!!:~!~~~~~~~~!B~             :Y^^^^^^:BG^^^:.YP~^^BJ :^^^^^^^^^^^^^^^^^^^5G^^^^^!Y.                                                                     .  .::..:::::::::J@@5:  :~!!~::^^::~JGP?~^::7J         .~!.         ......?P.  :~!?Y?:............................................................
                                                                                           .G?  :~!~~~~!!^~~~~~~~~~~5P              ^7:^^^^^!@J:^^::GP~^J#^.^^^^^^^^^^^^^^^^^^^7#7^^^~P7                                                                       .:. .:::.::::::!&#! .^~~~^:::::^?55??!:^^::!Y.  .....:~^      ......... ~P:  .~7J?^..............................................................
                                                                                            ^B^  :~~~~~~7~~~~~~~~~~~7B!              ~!:^^^^:Y&~:^^.~B5^~BY :^^^^^^^^^^^^^^^^^^^GP^^^YB:                                                                     ..  .::..:::::::^G@7.^~^^:^::::!JY?!^^77:^^::!5:...  .:^.   ........     ^P^  .!7!:................................................................
                                                                                             ?P   :!~~~~!7~~~~~~~~~~7GP.              7^^^^^^^BG.^^^.?#J^?&^ ^^^^^^^^^^^^^^^^^^^?#7^?&? .                                   ::                             .   .:..::::::::::5@Y^^^::::::~?G5!^^^^^!?:^^:^!5:    ...  ......     ....:5~  .^^:..................................................................
                                                                                              P7   ^!~~~~!7~~~~~~~~~~5&7              .7:^^^^^~&?.^^^.5&?^BP :^:^^^^^^^^^^^^^^^^^GP!#G!!^~^                           ..^~~~!?~                            ......:::.:::::::?@P^::::::^!7!:Y?^^^^^^!?:^^::~5: ...   ....    .........J~   ......................................................................
                                                                                              ^G.  .~~~~~!7~~~~~~~~~~!B#:              ^!:^^^^:J&^:^^^:G#7?&! ^::^^^^^^^^^^^^^^^^?###?^  .~~.                      .:^^^^:.^~!Y~..                      . ......:.:::::::::7@G^::::^~!~:   ?7:^^^^^!?:^^::~P^...       .............!~   .......................................................................
                                                                                               J?   :~~~~~!!~~~~~~~~~~7#5               !~:^^^^^GG.:^^:!#B!GG..^:^^^^^^^^^^^^^^^^~B&?.    .7?.                  .:::.      :~~7J::                      . .....:::::::::::7&B~:::^^^:......?? ..:^^~?^^^::~P^     .................^^  .........................................................................
                                                                                               :Y.   ~!~~~!!~~~~~~~~~~~J#7              .7::^^^^!&J ^^^:?&G?&7 :^:^^^^^^^^^^^^^:~G#7       :J7               ..:..         .~~~J~:.                    ......::.:::::::::7&B^.::::........ !J    ..^?^^^:^~P! ....................::  ..........................................................................
                                                                                                !~   :~~~~~!!~!~~~~~~~~~YP:              :?~^^^^^Y&^.^^^^5@PPB..^::^^^^^^^^^^^^7GB~         ~?^.          .....             ~~~??::.                 .....::..::::::::::!&B^.::......      !Y      .7^^^:^^P?....................:. ............................................................................
                                                                                                .7.  .~~~~~~7~~~~~~~~~~~~??.              ~5~^^^^^BG.:^^^^G&G&? :^:^^^^^^^^^^~?P5.          ^7?:.      ....                 ^~~!J^::              .....:::.::::::::::::7&G^.:....     .....!5       !^^^:^^P7...................................................................................................
                                                                                                 ^:   ^!~~~~!!^~!~~~~~~~~~!!.              ?5^^^^^!&J :^^^~#&##: ^^:^^^^^^^^!JJ7            .~J!::......                    ^!~~J~::.       .  .... .::..:::::::::::::?&P:..      ........ ^5.      !~^^:^^5?...................................................................................................
                                                                                                 .:   ^!~~~~~!!^~~~~~~~~~~~!!~.            .5?:^^^^J&~ ^^^^7&&@Y .^::^^^^^:7J?^              :!Y^:::.                       ^!~~77:::.   ..  .:. .:::..:::.::::::::::J@Y     ........      ^P:      !~^^:^^5Y...................................................................................................
                                                                                                  ~.  ^!~~~~~~!!~~~~~~~~~~~~^?B^            ^P^^^^^^GB..^^^^J&@&^ ^^::^^^^7J?^                :J!..                         ^!~~7J::::::. .::. :::..::::::::::::::::Y&?  .......      .....^G:      ~~^^:^^55...................................................................................................
                                                                                                  ?~  ^!~~~~~~~~!!~~~~~~~~~~~ PP             ?J :^^^~&Y :^^^^P@@P .^^:^^^7JJ~                 .^:                           ^!~~!J^:::..:::..:::.:::::::::::::::::^G#!.....       .........:P^      ~!^^:^^YP...................................................................................................
                                                                                                  JY  ^!~~~~~~~~~7!~~~~~~~~~~:?@?.           .Y^ .:^^?@~ :^^^~B@@! :^::^!JYJ                                                ^~~~!J^::::::.:::::::::::::::::::::::!BG^        ..............:P~      ^!^^:^^YG...................................................................................................
                                                                                                  YP  ^!~~~~~~~~~!?!~~~~~~~?YYJYG#?           ^Y....::P#. ^^^^7&@B: ^^.^JPG:                                                ~~~~!Y^:::::::::::::::::::::::::::::?#Y.    ....................P7      ^!^^:^^JG:..................................................................................................
                                                                                                  5P .~~~~~~~~~~~~!?!~~~~?PJ!~^~!J#Y           ?7 .:..:#5 .^^^^J@@Y .^:7GB^                                                 ~~~~!Y~::::::::::^^^^~~^~~::::::::^5#!  ........................PJ      :7^^:^^?B:..................................................................................................
                                                                                                  G5 ^!~~~~~~~~~~~~77~~~J#7^~~~~~~7#Y          .5^ ..:.7&! .^^^~G@#: :!B#^                                                 .~~~~!J~::::::^~~~~~^:::.^7.::::::~BP^...........................5Y      :7^^:^^7B^..................................................................................................
                                                                                                 :&7.~~~~~~~~~~~~~~~7~~J#7~~~~~~~~~!B5.         ~P. ....5#: :^^^!#@? .G&~                                                  :!~~~~?^::^~!!!~^^^^^~~~^!!.:::::JB?.............................J5      :7^^:^^7#~..................................................................................................
                                                                                                 J#:^!~~~~~~~~~~~~~~!!?#7^!~~~~~~~7YPP^          ~.   ..^#5  :^^^?@G.Y&~                                                   ^!~~~~?!~!7!!~~~~!!!!~!~^J:.:::7BP~..............................?P      .7~^:^^7#~..................................................................................................
                                                                                                :&J.~~~~~~~~~~~~~~~~!?GY:~~~~~~!7??##^               ..  ?&!  .::^5#P&!                                                   .~~~~~~??!!~~~~~~~~~~~!~:!J :::Y#?................................?B.     .7~^:^^!#~..................................................................................................
                                                                                                5#:^!~~~~~~~~~~~~~~~!PB~~~~~~~?J?755:                .::..PB:     .G@?                                                    ^!~~~~~~~~~~~~~~~~~~^~!^~J! :^PG^.................................7B.     .7~^:^^~#7..................................................................................................
                                                                                               !&7:!~~~~~~~~~~~~~~~~7#?~~~~~7YJ!!7~                    .::~#Y     ?&J                                                    .~~~~~~~~~~~~~~~~~~~~!~^~!Y:.~G5:..................................~G:      7!^:^.:#?..................................................................................................
                                                                                              .BP:~~~~~~~~~~~~~~~~~!P5~~~~!Y57!!:                        ..J&~   7@5                                                     :!~~~~~~~~~~~~~~~~~~!!:^~7? ~BY....................................:J:      7!^:  :G7..................................................................................................
                                                                                              J&7~~~~~~~~~~~~~~~~~~YG~~~~?5J!7!.                    .?:    .GG. ~&G.                                                    .~~~~~~~~~~~~~~~~~~~!!::^~?:~#G^....................................:J^      !7.  ..J!..................................................................................................
                                                                                             :&5~~~~~~~~~~~~~~!!!!5B7~~!YY7!7^                      .7:     ^&?^##:                                                     ^!~~~~~~~~~~~~~~~~^~!:^~~7?7P57......................................7~      ~~ .:. !7..................................................................................................
                                                                                             5#!~~~~~~~~~~~~~~!~~YG!~~7J7!!^                                 ?&#&~                                                     .~~~~~~~~~~~~~~~~~~~!^:~~~YPY77:......................................^:      ~!.:   75..................................................................................................
                                                                                            ~B!^!~~~~~~~~~~!!~~7PP!~!??!~:         ......................    .#@?                                                      ^!~~~~~~~~~~~~~~!~^!^:~~~JBJ!?^.......................................^.      ^7.    JG..................................................................................................
                                                                                           .5~ :!~~~~~~~~~!!~!Y#Y^~!??7^...............................^~    ?@P                                                      .~~~~~~~~~~~~~~~~!7!::~~~?G?!Y~.......................................:J:      ^?    .5G..................................................................................................
                                                                                           ~#! .~!~~~~~~!!~!?GP~:~!?J!:................................:^.  .B&^                                                      ^!~~~~~~~~~~~~~~~~!:^~~~Y#?!Y~........................................:GJ      ^7   ..!~..................................................................................................
                                                                                           ^#J   ^~~~~~!!~!YY~:^~!?7^...................................:!. ?@?                                                      .~!~~~~~~~~~~~~~~!~.^!~~Y&J7Y~..........................................?Y      :! .:.  ...................................................................................................
                                                                                            ^55J7~~~!!!~~?Y7^^~~7?~......................................~^~&B.                                                      ^!~~~~~~~~~~~~~~7~:~!~~?BJ7Y^.............................................        ..    ...................................................................................................
                                                                                              :~!JY55Y?YG?!77!?Y?:..................................      .G@!                                                      .~~~~~~~~~~~~~~~!^^~!~~!Y??J^...............................................      ^.     ...................................................................................................
                                                                                                  ..::.^J77J7^^:...........................               ?@G.                                                      ^!~~~~~~~~~~~~~!^:~!~~!J???:..............................................        :      ...................................................................................................
		");
	}

	override function update(elapsed:Float)
	{
		super.update(elapsed);
		if (FlxG.keys.justPressed.BACKSPACE || FlxG.keys.justPressed.ESCAPE) {
			MusicBeatState.switchState(new MainMenuState());
		}
	}
}

// YOOOOOO WHAT AMI
